### ISSUE TITLE
[FEAT] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by moondrop0816** [moondrop0816/flip#1]
## Description
프로젝트 초기 세팅

## Todo

- [x] eslint, prettier 설정 
- [x] husky 
    - [x] commit message 설정
            브랜치 이름 뒤에 이슈 번호를 붙이고 커밋에 이슈 번호 붙게 하기 
    - [x] 커밋시 변경된 파일에만 린팅하기
    - [x] main, dev로 직접 push 방지하기
