### ISSUE TITLE
[FEAT] 회원가입 구현

### ISSUE THREAD

**Issue by moondrop0816** [moondrop0816/flip#3]
## Description
Firebase를 이용한 회원가입 구현(디자인은 별도의 이슈로 작성)

## Todo

- [x] react-hook-form을 사용하여 구현
  - [x] 이메일 중복 확인
  - [x] 비밀번호 유효성 검사
  - [x] 폼 제출
