### ISSUE TITLE
[FEAT] 게시글 좋아요, 홈화면

### ISSUE THREAD

**Issue by moondrop0816** [moondrop0816/flip#34]
## Description
게시글 좋아요 구현, 홈 화면 작성

## Todo

- [x] 좋아요
  - [x] 본인이 작성한 게시글을 포함한 모든 게시글에 좋아요를 할 수 있음 
- [x] 홈 화면
  - [x] 로그인 하지 않아도 접근할 수 있게 하기 
  - [x] 기본 화면 구현
