### ISSUE TITLE
[FEAT] 실시간 채팅 구현

### ISSUE THREAD

**Issue by moondrop0816** [moondrop0816/flip#42]
## Description
실시간 채팅 기능 구현

## Todo

- [ ]  Firebase를 이용한 실시간 채팅 기능 구현
- [ ]  채팅 메시지 보내기
- [ ]  채팅 메시지 받기
- [ ]  채팅 목록 페이지 구현
